[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.json"
  [headers.values]
    Access-Control-Allow-Origin = "*"
